# Configuration preset used on Wizard's Den Salamander

[game]
desc = "Official English Space Station 14 servers. Medium roleplay ruleset. You must apply for a whitelist to join on the official forums, or have enough time on any Wizard's Den servers and the current playercount is less then 15."
hostname = "[EN][MRP] Wizard's Den Salamander [US West]"
round_restart_time = 300

[server]
rules_file = "MRPRuleset"

[whitelist]
enabled = true
prototype_list = "salamanderMrpWhitelist"

[shuttle]
emergency_early_launch_allowed = true

[biomass]
easy_mode = false

[ooc]
enable_during_round = false

[ic]
flavor_text = true

[hub]
tags = "lang:en,region:am_n_w,rp:med"

